import { Hono } from 'hono';
import { eq } from 'drizzle-orm';
// @ts-ignore — no types for subpath
import QRCode from 'qrcode/lib/browser.js';

import { createDb } from '@/db';
import { orders } from '@/db/schema';
import { getStorage } from '@/lib/storage';
import type { Env } from '@/types/env';

export const voucherRoutes = new Hono<{ Bindings: Env }>();

// GET /api/vouchers/:voucherNumber/qr — stream QR SVG from storage
voucherRoutes.get('/:voucherNumber/qr', async (c) => {
  const voucherNumber = c.req.param('voucherNumber');
  if (!voucherNumber) return c.json({ error: 'Voucher number required' }, 400);

  const storage = getStorage();
  const db = createDb();
  const [order] = await db
    .select({ voucherQrKey: orders.voucherQrKey, voucherNumber: orders.voucherNumber })
    .from(orders)
    .where(eq(orders.voucherNumber, voucherNumber))
    .limit(1);

  if (!order || !order.voucherQrKey) return c.json({ error: 'Voucher not found' }, 404);

  let obj = await storage.get(order.voucherQrKey);
  // Lazy-regenerate QR if missing (creation-time upload may have failed, but order has all data to rebuild)
  if (!obj) {
    const db2 = createDb();
    const [o2] = await db2
      .select({ orderNumber: orders.orderNumber, invoiceAccessToken: orders.invoiceAccessToken })
      .from(orders)
      .where(eq(orders.voucherNumber, voucherNumber))
      .limit(1);
    if (o2?.orderNumber && o2?.invoiceAccessToken) {
      try {
        const invoiceUrl = `${c.env.APP_URL.replace(/\/$/, '')}/invoices/${encodeURIComponent(o2.orderNumber)}?token=${encodeURIComponent(o2.invoiceAccessToken)}`;
        const svg: string = await new Promise<string>((resolve, reject) => {
          // @ts-ignore — no types for subpath
          QRCode.toString(invoiceUrl, { type: 'svg', width: 400, margin: 1, errorCorrectionLevel: 'M', color: { dark: '#000000', light: '#FFFFFF' } }, (err: Error | null, res: string) => err ? reject(err) : resolve(res));
        });
        const bytes = new TextEncoder().encode(svg);
        // Try to cache in storage, but always return directly even if put fails
        try {
          await storage.put(order.voucherQrKey, bytes, 'image/svg+xml');
          obj = await storage.get(order.voucherQrKey);
        } catch {}
        // If storage still miss, return generated bytes directly (100% reliable)
        if (!obj) {
          return new Response(bytes, {
            headers: {
              'Content-Type': 'image/svg+xml',
              'Cache-Control': 'public, max-age=31536000, immutable',
            },
          });
        }
      } catch (e) {
        console.error('[VOUCHER] lazy QR regen failed', e);
        // Return debug info so deploy can be verified (remove in prod hardening)
        return c.json({ error: 'QR regen failed', detail: e instanceof Error ? e.message : String(e) }, 500);
      }
    }
  }
  if (!obj) return c.json({ error: 'QR not found' }, 404);

  return new Response(obj.body, {
    headers: {
      'Content-Type': obj.contentType,
      'Cache-Control': 'public, max-age=31536000, immutable',
      ETag: obj.httpEtag,
    },
  });
});

// GET /api/vouchers/:voucherNumber — voucher metadata (for admin verification)
voucherRoutes.get('/:voucherNumber', async (c) => {
  const voucherNumber = c.req.param('voucherNumber');
  const db = createDb();
  const [order] = await db
    .select({
      id: orders.id,
      orderNumber: orders.orderNumber,
      voucherNumber: orders.voucherNumber,
      voucherQrKey: orders.voucherQrKey,
      total: orders.total,
      status: orders.status,
      createdAt: orders.createdAt,
    })
    .from(orders)
    .where(eq(orders.voucherNumber, voucherNumber))
    .limit(1);
  if (!order) return c.json({ error: 'Voucher not found' }, 404);
  return c.json({ success: true, data: order });
});
